<?php
/**
 * Get the plugin classmap
 *
 * @package Teydea_Studio\Password_Requirements
 */

return [
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Universal_Modules\\Module_Cache_Invalidation' => '/deps/php/universal-modules/class-module-cache-invalidation.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Universal_Modules\\Module_Endpoint_Settings' => '/deps/php/universal-modules/class-module-endpoint-settings.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Universal_Modules\\Module_Plugin_Row_Meta' => '/deps/php/universal-modules/class-module-plugin-row-meta.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Universal_Modules\\Module_Plugin_Upgrade_Action_Link' => '/deps/php/universal-modules/class-module-plugin-upgrade-action-link.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Universal_Modules\\Module_Settings_Page' => '/deps/php/universal-modules/class-module-settings-page.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Universal_Modules\\Module_Translations' => '/deps/php/universal-modules/class-module-translations.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\Asset' => '/deps/php/utils/class-asset.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\Cache' => '/deps/php/utils/class-cache.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\Container' => '/deps/php/utils/class-container.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\Environment' => '/deps/php/utils/class-environment.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\JSON' => '/deps/php/utils/class-json.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\Module' => '/deps/php/utils/class-module.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\Nonce' => '/deps/php/utils/class-nonce.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\Plugin' => '/deps/php/utils/class-plugin.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\Screen' => '/deps/php/utils/class-screen.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\Settings' => '/deps/php/utils/class-settings.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\Strings' => '/deps/php/utils/class-strings.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\Type' => '/deps/php/utils/class-type.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\Uninstall' => '/deps/php/utils/class-uninstall.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\User' => '/deps/php/utils/class-user.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Utils\\Users' => '/deps/php/utils/class-users.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Validatable_Fields\\Configuration' => '/deps/php/validatable-fields/class-configuration.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Validatable_Fields\\Dynamic_Fields_Group' => '/deps/php/validatable-fields/class-dynamic-fields-group.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Validatable_Fields\\Field' => '/deps/php/validatable-fields/class-field.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Validatable_Fields\\Field_Array_Of_Strings' => '/deps/php/validatable-fields/class-field-array-of-strings.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Validatable_Fields\\Field_Boolean' => '/deps/php/validatable-fields/class-field-boolean.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Validatable_Fields\\Field_Integer' => '/deps/php/validatable-fields/class-field-integer.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Validatable_Fields\\Field_String' => '/deps/php/validatable-fields/class-field-string.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Validatable_Fields\\Field_String_Of_Choice' => '/deps/php/validatable-fields/class-field-string-of-choice.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Validatable_Fields\\Fields_Group' => '/deps/php/validatable-fields/class-fields-group.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Validatable_Fields\\Key_Identifiable' => '/deps/php/validatable-fields/trait-key-identifiable.php',
	'Teydea_Studio\\Password_Requirements\\Dependencies\\Validatable_Fields\\Validatable' => '/deps/php/validatable-fields/trait-validatable.php',
	'Teydea_Studio\\Password_Requirements\\Modules\\Module_Compliance_On_Interaction' => '/src/modules/class-module-compliance-on-interaction.php',
	'Teydea_Studio\\Password_Requirements\\Modules\\Module_Compliance_On_Login' => '/src/modules/class-module-compliance-on-login.php',
	'Teydea_Studio\\Password_Requirements\\Modules\\Module_Compliance_On_Password_Change' => '/src/modules/class-module-compliance-on-password-change.php',
	'Teydea_Studio\\Password_Requirements\\Modules\\Module_Password_Hint' => '/src/modules/class-module-password-hint.php',
	'Teydea_Studio\\Password_Requirements\\Modules\\Module_Plugin_Upgrade_Action_Link' => '/src/modules/class-module-plugin-upgrade-action-link.php',
	'Teydea_Studio\\Password_Requirements\\Modules\\Module_Settings_Page' => '/src/modules/settings-page/class-module-settings-page.php',
	'Teydea_Studio\\Password_Requirements\\Modules\\Module_Site_Health' => '/src/modules/class-module-site-health.php',
	'Teydea_Studio\\Password_Requirements\\Password_Policy' => '/src/class-password-policy.php',
	'Teydea_Studio\\Password_Requirements\\Passwords_Store' => '/src/class-passwords-store.php',
	'Teydea_Studio\\Password_Requirements\\Settings' => '/src/class-settings.php',
	'Teydea_Studio\\Password_Requirements\\User' => '/src/class-user.php',
];
